### ISSUE TITLE
Research Project

### ISSUE THREAD

**Issue by synacktic** [devshane/majorbbs#1]
Thanks for putting this up! Do you have any other versions of the source? I am wanting to create a git of MajorBBS through Worldgroup with branches for each release. This is just for me to learn more about git and I'm thinking of something like this project: https://github.com/dspinellis/unix-history-repo

It does not need to be a public repo, but could be if various parties agreed. 

Thanks in any case, @devshane

**Comment by devshane** [comment]
Unfortunately not. I've tried over the years to locate more recent versions but this is all I've been able to find. None of the 10+ former employees that I'm still in contact with have anything either. I was there in the early 1990s, v6.x up through Worldgroup.

Have you tried https://www.themajorbbs.com? I think that's Rick Hadsall's (Elwynor Technologies) thing. He was keen on modernizing and resurrecting Worldgroup, though I last heard from him in 2012.

Good luck! If you find anything please let me know.
